name:                yesod-bulma
version:             0.2.0.0
github:              "waddlaw/yesod-bulma"
license:             BSD3
author:              "Shinya Yamaguchi"
maintainer:          "ingroze@gmail.com"
copyright:           "Copyright (c) 2018 Shinya Yamaguchi"
synopsis:            support Bulma form for Yesod
category:            Web, Yesod

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/waddlaw/yesod-form-bulma#readme>

dependencies:
- base >= 4.7 && < 5
- email-validate
- shakespeare
- text
- uri-encode
- yesod-core
- yesod-form
- yesod-paginator

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wnoncanonical-monad-instances
- -Wredundant-constraints
- -Wtabs

library:
  source-dirs: src

executables:
  form-example:
    main: app/Example.hs
    dependencies:
      - yesod-bulma
      - yesod
  form-showcase:
    main: app/Showcase.hs
    dependencies:
      - yesod-bulma
      - yesod
  paginator-example:
    main: app/Paginator.hs
    dependencies:
      - yesod-bulma
      - yesod

tests:
  yesod-form-bulma-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yesod-bulma
