name:                yesod-form-bulma
version:             0.1.0.0
github:              "waddlaw/yesod-form-bulma"
license:             BSD3
author:              "Shinya Yamaguchi"
maintainer:          "ingroze@gmail.com"
copyright:           "Copyright (c) 2018 Shinya Yamaguchi"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/waddlaw/yesod-form-bulma#readme>

dependencies:
- base >= 4.7 && < 5
- text
- yesod-form
- shakespeare
- yesod-core

library:
  source-dirs: src

tests:
  yesod-form-bulma-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yesod-form-bulma
